### ISSUE TITLE
Addons don't run when a page is changed in Edge

### ISSUE THREAD

**Issue by mybearworld** [imadeanaccount1/wasteof.plus#49]

**Comment by imadeanaccount1** [comment]
@mybearworld  How did you install the extension? In this update, `npm run ci` must be run before the addon can be loaded into Chrome, Edge, or Opera. Otherwise, a build is currently being made under Actions that will contain a downloadable release artifact. The extension styles use Tailwind in this update, which is why you must install the dependencies.

**Comment by imadeanaccount1** [comment]
I justed tested this with the build in https://github.com/imadeanaccount1/wasteof.plus/actions/runs/5693794806, and it's working fine in Edge for me: 
![image](https://github.com/imadeanaccount1/wasteof.plus/assets/138229538/50da9965-c94e-4961-bf10-bfa8fb24f971)

**Comment by mybearworld** [comment]
Same issue as #48, I didn't realize dependencies changed. Sorry!
